default["wpapp"]["database"] = "wpapp"
default["wpapp"]["db_username"] = "wpapp"
default["wpapp"]["db_password"] = "wpapppass"
default["wpapp"]["path"] = "/var/www/wpapp"
default['wpapp']['server_name'] = "wpapp"
